#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:$OPENSHIFT_DIY_PORT

# just perl
#DANCER_PORT=$OPENSHIFT_DIY_PORT DANCER_SERVER=$OPENSHIFT_DIY_IP nohup ~/app-root/data/perl-new/bin/perl $OPENSHIFT_REPO_DIR/diy/app.pl |& /usr/bin/logshifter -tag diy &

# PLACKUP
nohup ~/app-root/data/perl-new/bin/perl ~/app-root/data/perl-new/bin/plackup --host $OPENSHIFT_DIY_IP --port $OPENSHIFT_DIY_PORT $OPENSHIFT_REPO_DIR/diy/app.pl |& /usr/bin/logshifter -tag diy &

# STARMAN (with 10 workers)
#nohup ~/app-root/data/perl-new/bin/perl ~/app-root/data/perl-new/bin/starman --workers 10 --host $OPENSHIFT_DIY_IP --port $OPENSHIFT_DIY_PORT ~/app-root/runtime/repo/diy/app.pl |& /usr/bin/logshifter -tag diy &
